# Default configuration
%dev.quarkus.dynamodb.aws.region=us-east-1
%dev.quarkus.dynamodb.endpoint-override=http://localhost:4566
%dev.quarkus.dynamodb.aws.credentials.type=static
%dev.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=dummy
%dev.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=dummy

# Production profile (Docker)
%prod.quarkus.dynamodb.aws.region=us-east-1
%prod.quarkus.dynamodb.endpoint-override=http://localstack:4566
%prod.quarkus.dynamodb.aws.credentials.type=static
%prod.quarkus.dynamodb.aws.credentials.static-provider.access-key-id=dummy
%prod.quarkus.dynamodb.aws.credentials.static-provider.secret-access-key=dummy

quarkus.package.jar.type=mutable-jar

quarkus.log.category."software.amazon.awssdk".level=DEBUG